language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
  - '4'
before_install:
  - npm i -g npm@3.10.10
  - export CHROME_BIN=chromium-browser
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
